Make geo more optimized
holoviz/hvplot pull request #1353
Opened 2024-06-13 23:03 UTC by ahuang11

1. Batch call watchers so the loading symbol doesn't flicker (just tabbed everything over)
2. If scatter/line, swap to points/path
3. Projection doesn't always seem to be provided, so use crs instead

2024-06-17 17:04 UTC, ahuang11 commented on hvplot/ui.py
> +            raise e
Intentional while debugging :) but not meant to be pushed.

2024-06-17 17:04 UTC, ahuang11 commented on hvplot/ui.py
> +                kwargs['projection'] = kwargs['crs']
I guess not with this guard
https://github.com/holoviz/hvplot/pull/1353/commits/c4c1c7522ac0a56d913ab13df443575a84d45ec5#diff-e8e2b619a805d78b88c365301a48695ea26e0f325c0662ff25af3e791b90be86R679

2024-06-18 08:52 UTC, maximlt approved these changes

2024-06-18 08:54 UTC, maximlt requested changes
Ah in fact there are two failing tests:

```
FAILED hvplot/tests/testui.py::test_explorer_geo_revise_kind[kind_tuple0] - TypeError: Constant parameter 'geo' cannot be modified
FAILED hvplot/tests/testui.py::test_explorer_geo_revise_kind[kind_tuple1] - TypeError: Constant parameter 'geo' cannot be modified
```

2024-06-27 22:46 UTC, ahuang11 commented
New test failure; prob should handle in a separate PR.
`AttributeError: The geopandas.dataset has been deprecated and was removed in GeoPandas 1.0. You can get the original 'naturalearth_cities' data from [https://www.naturalearthdata.com/downloads/110m-cultural-vectors/.](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/)`

2024-07-16 14:20 UTC, maximlt approved these changes

2024-07-16 14:20 UTC, merged